LABS-463 add functionality to read and set windowid field
mongodb-labs/labs-modules pull request #34
Opened 2022-10-09 04:56 UTC by Z-Shang

2022-10-09 23:41 UTC, steve-1820 commented
LGTM

2022-10-09 23:41 UTC, steve-1820 approved these changes

2022-10-09 23:41 UTC, steve-1820 approved these changes

2022-10-10 01:05 UTC, steve-1820 requested changes

2022-10-10 01:05 UTC, steve-1820 commented on src/windowing/document_source_coprime_timed_slide_window.cpp
> +          Value(getStageId().toString() + "-" + std::to_string(_totalWindow)));
@Z-Shang Do we use this for concurrency tests (i.e. for the composite key during $group)? If so, how does this work during a restart when _totalWindow will be reset?

2022-10-10 03:04 UTC, Z-Shang commented on src/windowing/document_source_coprime_timed_slide_window.cpp
> +          Value(getStageId().toString() + "-" + std::to_string(_totalWindow)));
good point, let me concat an additional timestamp to prevent this from happening

2022-10-10 03:40 UTC, michaelcahill approved these changes

2022-10-11 04:00 UTC, steve-1820 commented on src/windowing/document_source_coprime_timed_slide_window.cpp
> +          Value(getStageId().toString() + "-" + std::to_string(_totalWindow)));
Cool, thanks for changing @Z-Shang LGTM

2022-10-11 04:00 UTC, steve-1820 approved these changes

2022-10-11 04:01 UTC, merged