LABS-448 align mongo repo branch and labs-modules branch
mongodb-labs/labs-modules pull request #35
Opened 2022-10-11 23:24 UTC by steve-1820

2022-10-11 23:39 UTC, Z-Shang requested changes

2022-10-11 23:39 UTC, Z-Shang commented on jstests/stream/checkpoint.js
> +load("src/mongo/db/modules/labs/jstests/stream/utils/stream.js
missing a `");` at the end of line?

2022-10-11 23:39 UTC, Z-Shang commented on jstests/stream/create_stream.js
> +load("src/mongo/db/modules/labs/jstests/stream/utils/stream.js
missing a "); at the end of line?

2022-10-11 23:47 UTC, steve-1820 commented on jstests/stream/checkpoint.js
> +load("src/mongo/db/modules/labs/jstests/stream/utils/stream.js
@Z-Shang great catch - will fix

2022-10-12 00:19 UTC, Z-Shang approved these changes

2022-10-12 01:16 UTC, michaelcahill approved these changes
lgtm

2022-10-12 02:18 UTC, merged